import Head from "next/head";
import CustomNavbar from "../components/CustomNavbar";
import React from "react";

export default function Terms() {
  return (
    <div className="min-h-screen bg-[#FAFAFA] font-sans flex flex-col">
      <Head>
        <title>Terms of Service - LMEvals</title>
      </Head>
      <CustomNavbar />

      <main className="flex-1 flex flex-col items-center justify-center px-6 mt-6">
        <div className="w-full max-w-3xl mx-auto mt-24 mb-16 rounded-2xl p-8">
          <h1 className="text-4xl font-bold text-gray-900 mb-6">Terms of Service</h1>
          <p className="text-base text-gray-700 mb-4">
            Welcome to LMEvals. By accessing or using our website and services, you agree to be bound by the following terms and conditions. Please read them carefully.
          </p>
          <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-2">1. Use of Service</h2>
          <p className="text-base text-gray-700 mb-4">
            LMEvals provides a platform for users to create, run, and share large language model (LLM) evaluations. You are solely responsible for your use of the service, including any content you submit, generate, or share.
          </p>
          <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-2">2. User Content</h2>
          <p className="text-base text-gray-700 mb-4">
            All content, evaluations, prompts, and results are generated by users or by third-party AI models at the request of users. LMEvals does not endorse, verify, or guarantee the accuracy, reliability, or appropriateness of any content or results produced on the platform.
          </p>
          <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-2">3. Disclaimers</h2>
          <ul className="list-disc pl-6 text-base text-gray-700 mb-4">
            <li>
              <span className="font-semibold">No Endorsement:</span> The opinions, scores, and outputs generated on LMEvals are not the opinions of LMEvals, its owners, or its affiliates. They are the product of automated systems and/or user input.
            </li>
            <li>
              <span className="font-semibold">No Warranty:</span> LMEvals is provided "as is" and "as available" without warranties of any kind, either express or implied. We do not guarantee that the service will be uninterrupted, error-free, or secure.
            </li>
            <li>
              <span className="font-semibold">No Liability:</span> LMEvals, its owners, operators, and affiliates are not liable for any damages, losses, or consequences resulting from your use of the service, including but not limited to any reliance on information, results, or content generated by the platform.
            </li>
            <li>
              <span className="font-semibold">User Responsibility:</span> You are solely responsible for any actions you take based on the outputs or information provided by LMEvals. Do not use LMEvals for any unlawful, harmful, or high-stakes purposes.
            </li>
          </ul>
          <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-2">4. Limitation of Liability</h2>
          <p className="text-base text-gray-700 mb-4">
            To the fullest extent permitted by law, LMEvals and its affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from (a) your use or inability to use the service; (b) any unauthorized access to or use of our servers and/or any personal information stored therein; (c) any content or conduct of any third party on the service.
          </p>
          <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-2">5. Changes to Terms</h2>
          <p className="text-base text-gray-700 mb-4">
            We may update these Terms of Service from time to time. Continued use of LMEvals after any changes constitutes your acceptance of the new terms.
          </p>
          <div className="mt-8 text-sm text-gray-400 italic">
            Last updated: May 2025
          </div>
        </div>
      </main>

      <footer className="relative border-t border-black/5 bg-white">
        <div className="max-w-7xl mx-auto py-12 px-6">
          <div className="flex flex-col md:flex-row justify-between items-center gap-8">
            <div className="flex flex-col">
              <span className="text-black/70 text-sm">© 2025 LMEvals. All rights reserved.</span>
            </div>
            <nav className="flex items-center space-x-8">
              <a href="/terms" className="text-black/70 hover:text-black text-sm transition-colors duration-200">Terms</a>
            </nav>
          </div>
        </div>
      </footer>
    </div>
  );
}
